# Configuração do site
title: "Minha Adega Digital"
description: "Notas e impressões pessoais sobre meus whiskies"

# Configuração do Jekyll
markdown: kramdown
#theme: jekyll-theme-primer  # Tema leve e limpo (opcional)
theme: minima 

# URLs amigáveis
permalink: pretty

collections:
  degustacoes:
    output: true
    permalink: /degustacoes/:path/

# Pastas que não devem ser processadas
exclude:
  - README.md
  - .gitignore
